const China = [
    {
        name: 'Hubei',
        population: 5917,
        confirmed: 67790,
        deaths: 3075,
    },
    {
        name: "Guangdong",
        population: 11346,
        confirmed: 1356,
        deaths: 8,
    },
    {
        name: 'Henan',
        population: 9605,
        confirmed: 1273,
        deaths: 22,
    },
    {
        name: 'Zhejiang',
        population: 5737,
        confirmed: 1227,
        deaths: 1,
    },
    {
        name: 'Anhui',
        population: 6324,
        confirmed: 935,
        deaths: 6,
    },
    {
        name: 'Jiangxi',
        population: 4648,
        confirmed: 935,
        deaths: 1,
    },
    {
        name: 'Shandong',
        population: 10047,
        confirmed: 760,
        deaths: 7,
    },
    {
        name: 'Jiangsu',
        population: 8051,
        confirmed: 631,
        deaths: 0,
    },
    {
        name: 'Chongqing',
        population: 3102,
        confirmed: 576,
        deaths: 6,
    },
    {
        name: 'Sichuan',
        population: 8341,
        confirmed: 539,
        deaths: 3,
    },
    {
        name: 'Heilongjiang',
        population: 3773,
        confirmed: 482,
        deaths: 13,
    },
    {
        name: 'Beijing',
        population: 2154,
        confirmed: 437,
        deaths: 8,
    },
    {
        name: 'Hebei',
        population: 7556,
        confirmed: 318,
        deaths: 6,
    },
    {
        name: 'Fujian',
        population: 3941,
        confirmed: 296,
        deaths: 1,
    },
    {
        name: 'Guangxi',
        population: 4926,
        confirmed: 252,
        deaths: 1,
    },
    {
        name: "Shannxi",
        population: 3864,
        confirmed: 245,
        deaths: 2,
    },
    {
        name: 'Yunnan',
        population: 4830,
        confirmed: 174,
        deaths: 2,
    },
    {
        name: 'Hainan',
        population: 934,
        confirmed: 168,
        deaths: 6,
    },
    {
        name: 'Guizhou',
        population: 3600,
        confirmed: 146,
        deaths: 2,
    },
    {
        name: 'HongKongSAR',
        population: 745,
        confirmed: 137,
        deaths: 4,
    },
    {
        name: 'Tianjin',
        population: 1546,
        confirmed: 136,
        deaths: 3,
    },
    {
        name: 'Shanxi',
        population: 3718,
        confirmed: 133,
        deaths: 0,
    },
    {
        name: 'Gansu',
        population: 2637,
        confirmed: 129,
        deaths: 2,
    },
    {
        name: 'Tianjin',
        population: 1546,
        confirmed: 136,
        deaths: 3,
    },
    {
        name: 'Gansu',
        population: 2637,
        confirmed: 129,
        deaths: 2,
    },
    {
        name: 'Liaoning',
        population: 4359,
        confirmed: 125,
        deaths: 1,
    },
    {
        name: 'Jilin',
        population: 2704,
        confirmed: 93,
        deaths: 1,
    },
    {
        name: "Xinjiang",
        population: 2487,
        confirmed: 76,
        deaths: 3,
    },
    {
        name: 'Ningxia',
        population: 688,
        confirmed: 75,
        deaths: 0,
    },
    {
        name: 'Inner Mongolia',
        population: 2534,
        confirmed: 75,
        deaths: 1,
    },
    {
        name: 'Taipei and Environs',
        population: 2359,
        confirmed: 50,
        deaths: 1,
    },
    {
        name: 'Qinghai',
        population: 603,
        confirmed: 18,
        deaths: 0,
    },
    {
        name: 'Macao SAR',
        population: 66,
        confirmed: 10,
        deaths: 0,
    },
    {
        name: 'Xizang',
        population: 344,
        confirmed: 1,
        deaths: 0,
    },
]

module.exports = China;
